// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import FileUploadController from "./file_upload_controller";
application.register("file-upload", FileUploadController);

import FlashController from "./flash_controller";
application.register("flash", FlashController);

import HackatimeProjectSelectorController from "./hackatime_project_selector_controller";
application.register(
  "hackatime-project-selector",
  HackatimeProjectSelectorController,
);

import HelloController from "./hello_controller";
application.register("hello", HelloController);

import ProjectFormController from "./project_form_controller";
application.register("project-form", ProjectFormController);

import PostAttachmentsController from "./post_attachments_controller";
application.register("post-attachments", PostAttachmentsController);

import ShopController from "./shop_controller";
application.register("shop", ShopController);

import VoteTrackerController from "./vote_tracker_controller";
application.register("vote-tracker", VoteTrackerController);

import DropdownController from "./dropdown_controller";
application.register("dropdown", DropdownController);

import ProjectIdeasController from "./project_ideas_controller";
application.register("project-ideas", ProjectIdeasController);

import AddressSelectController from "./address_select_controller";
application.register("address-select", AddressSelectController);

import OrderFormController from "./order_form_controller";
application.register("order-form", OrderFormController);

import LoadMoreController from "./load_more_controller";
application.register("load-more", LoadMoreController);

import ProjectFireController from "./project_fire_controller";
application.register("project-fire", ProjectFireController);
